echo "👋 kostyny"
echo "Git alias is load"
alias Gs="git status"
alias Gb="git branch"
alias Gst="git stash"
alias Gsta="git stash apply"
alias Gc-m="git commit -m"
alias Gc-a="git commit --amend"
alias Gp="git pull"
alias Gp-r="git pull --rebase"
alias Gp-rom="git pull --rebase origin master"
alias GP-romain="git pull --rebase origin main"
alias Gp="git push"
alias Gp-f="git push -f"
alias Gr-i="git rebase -i" 
alias Gr-a="git rebase --abort"
alias Gr-c"git rebase --continue"
alias Gf="git fetch"
alias Gfo="git fetch origin"
alias Gfom="git fetch origin/master"
alias Gfomain="git fetch origin/main"
alias Gru="git remote update"
alias Gad="git add ."
alias Ga="git add"
alias Gcb="git checkout -B"
alias Gc="git checkout"
alias Gsw="git switch"
alias Grs="git reset --soft"
alias Grh="git reset --hard"
alias Gbd="git branch -D"
alias Gcl="git clone"
alias Gpom-a="git pull origin main --allow-unrelated-histories"
alias Gm="git merge"
